# Triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Functions
jobs:
  # Build Job
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
      - name: Install NPM Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Cache dist directory
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  # Deploy Job
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          publish_dir: ./dist